name: Cache Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache-demo
          key: cache-eb74a6e

      - name: prime-cache-eb74a6e
        run: |
          echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"
          mkdir -p ~/.cache-demo
          echo "Saved at $(date)" > ~/.cache-demo/file.txt
